name: Update better attendance data

on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 5-10,13-15,20-22 * * MON-FRI' # 6h-11h, 14h-16h, 21h-23h
    - cron: '* 11-13,16-19 * * MON-FRI' # 12h-14h,17h-20h
    - cron: '*/10 5-7,14-22 * * SAT' # 8h-14h
    - cron: '* 8-13 * * SAT' # 8h-14h
    - cron: '*/10 2-22 * * SUN'
    - cron: '25 23,0,1 * * *' # 0h-2h

jobs:
  update-better-attendance-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - name: Install dependencies
        run: npm i --prefer-offline
      - id: update-better-attendance-file
        name: Update better attendance file
        run: npm run gh:update-better-attendance-file
        env:
          ORANGE_BLEUE_STUDIO_ID: ${{secrets.ORANGE_BLEUE_STUDIO_ID}}
          ORANGE_BLEUE_AUTH_TOKEN: ${{secrets.ORANGE_BLEUE_AUTH_TOKEN}}
          ORANGE_BLEUE_COOKIE: ${{secrets.ORANGE_BLEUE_COOKIE}}
          MAGICLINE_COOKIE: ${{secrets.MAGICLINE_COOKIE}}
      - id: check-empty-file
        name: Interrupt workflow
        run: |
          set +e
          git diff --quiet data/better-attendance.csv
          DIFF_EXIT_CODE=$?
          set -e

          if [ $DIFF_EXIT_CODE -ne 0 ]; then
              echo "better-attendance.csv has changed"
              echo "do-commit=true" >> $GITHUB_OUTPUT
          else
              echo "better-attendance.csv has not changed"
              echo "do-commit=false" >> $GITHUB_OUTPUT
          fi
      - uses: test-room-7/action-update-file@v2
        if: steps.check-empty-file.outputs.do-commit == 'true'
        with:
          file-path: data/better-attendance.csv
          commit-msg: ğŸ“¦ï¸ Update better-attendance.csv
          github-token: ${{ secrets.GITHUB_TOKEN }}
