name: Update attendance data

on:
  workflow_dispatch:
  schedule:
    - cron: '*/20 6-23 * * *'
    - cron: '25 0-2 * * *'

jobs:
  update-attendance-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v5
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - id: update-attendance-file
        name: Update attendance file
        run: npm run gh:update-attendance-file
      - id: check-empty-file
        name: Interrupt workflow
        run: |
          set +e
          git diff --quiet data/attendance.csv
          DIFF_EXIT_CODE=$?
          set -e

          if [ $DIFF_EXIT_CODE -ne 0 ]; then
              echo "attendance.csv has changed"
              echo "do-commit=true" >> $GITHUB_OUTPUT
          else
              echo "attendance.csv has not changed"
              echo "do-commit=false" >> $GITHUB_OUTPUT
          fi
      - uses: test-room-7/action-update-file@v2
        if: steps.check-empty-file.outputs.do-commit == 'true'
        with:
          file-path: data/attendance.csv
          commit-msg: ğŸ“¦ï¸ Update attendance.csv
          github-token: ${{ secrets.GITHUB_TOKEN }}
